eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8791/eureka/
  instance:
    hostname: localhost
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://localhost:8888/paymentprovider/payNow/    
